name: Generate API Docs

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 获取代码

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # 设置 Python 版本

      - name: Install dependencies
        run: |
          pip install sphinx  # 安装 Sphinx
          pip install pdoc3   # 安装 pdoc3

      - name: Generate API docs using Sphinx
        run: |
          sphinx-apidoc -o docs/source .  # 生成 Sphinx 文档
          sphinx-build -b html docs/source docs/build  # 构建文档为 HTML

      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: api-docs
          path: docs/build  # 将文档上传为 GitHub Action 产物
